name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Set version variables
      run: |
        # Use date-based version code: YYYYMMDDRRR (e.g., 20240115001)
        # Run number is padded to 3 digits to ensure monotonic increase
        DATE_CODE=$(date +%Y%m%d)
        RUN_NUMBER=$(printf "%03d" ${{ github.run_number }})
        VERSION_CODE="${DATE_CODE}${RUN_NUMBER}"
        VERSION_NAME="$(date +%Y.%m.%d).${{ github.run_number }}"
        echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        echo "Building with versionCode: $VERSION_CODE and versionName: $VERSION_NAME"
      
    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon
      
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
        
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{steps.sign_app.outputs.signedReleaseFile}}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
