name: Build APK

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Set version variables
      run: |
        # Use date-based version code: YYYYMMDD + run number (e.g., 20240115001)
        DATE_CODE=$(date +%Y%m%d)
        VERSION_CODE="${DATE_CODE}${{ github.run_number }}"
        VERSION_NAME="$(date +%Y.%m.%d).${{ github.run_number }}"
        echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        echo "Building with versionCode: $VERSION_CODE and versionName: $VERSION_NAME"
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
